/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dddSample

import UserRepository

class App {
    fun createUser(userName: String, firstName: String, lastName: String) {
        val user = User(
                UserName(userName),
                FullName(firstName, lastName))
        val userRepository = UserRepository()
        val userService = UserService(userRepository)
        if (userService.isDuplicated(user)) throw Exception("重複 : $user")
        userRepository.save(user)
    }
}

fun main(args: Array<String>) {
    println(App().createUser("id", "fname", "lname"))
}
