/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dddSample

class App {
    fun createUser(userName: String, firstName: String, lastName: String) {
        val user = User(
                UserName(userName),
                FullName(firstName, lastName))
        val userService = UserService()
        with(userService) {
            if (isDuplicated(user)) throw Exception("重複 : $user")
            // TODO: 登録
        }
    }
}

fun main(args: Array<String>) {
    println(App().createUser("id", "fname", "lname"))
}
